# Generated by Django 5.1.4 on 2024-12-07 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('contrasenia', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'accesos',
            },
        ),
        migrations.CreateModel(
            name='duracion_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_duracion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'duracion_plan',
            },
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_genero', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permiso', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='tipo_archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tipos_archivos',
            },
        ),
        migrations.CreateModel(
            name='tipos_lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lugar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_lugares',
            },
        ),
        migrations.CreateModel(
            name='tipos_modificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_modificacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos_modificaciones',
            },
        ),
        migrations.CreateModel(
            name='carpetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carpeta', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('id_carpeta_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.carpetas')),
            ],
            options={
                'db_table': 'carpetas',
            },
        ),
        migrations.CreateModel(
            name='archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=100)),
                ('fecha_guardado', models.DateField(blank=True, null=True)),
                ('archivo', models.BinaryField(blank=True, null=True)),
                ('tamanio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.carpetas')),
                ('id_tipo_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tipo_archivos')),
            ],
            options={
                'db_table': 'archivos',
            },
        ),
        migrations.CreateModel(
            name='lugares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(blank=True, max_length=500, null=True)),
                ('id_lugar_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.lugares')),
                ('id_tipo_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tipos_lugares')),
            ],
            options={
                'db_table': 'lugares',
            },
        ),
        migrations.CreateModel(
            name='ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.TextField(blank=True, null=True)),
                ('plan_id_duracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.duracion_plan')),
            ],
            options={
                'db_table': 'ofertas',
            },
        ),
        migrations.CreateModel(
            name='planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('espacio_almacenamiento', models.BigIntegerField(blank=True, null=True)),
                ('id_duracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.duracion_plan')),
                ('id_oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ofertas')),
            ],
            options={
                'db_table': 'planes',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('id_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.accesos')),
                ('id_tipo_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.genero')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='usuario_accesos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateField()),
                ('id_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.accesos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
            options={
                'db_table': 'usuario_accesos',
            },
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numuero_tarjeta', models.BigIntegerField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('firma_autorizada', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='modificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateField()),
                ('id_archivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.archivos')),
                ('id_tipo_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tipos_modificaciones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
            options={
                'db_table': 'modificaciones',
            },
        ),
        migrations.CreateModel(
            name='facturacion_planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_facturacion', models.DateField()),
                ('id_lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.lugares')),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.planes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios')),
            ],
            options={
                'db_table': 'facturacion_planes',
            },
        ),
        migrations.CreateModel(
            name='compartidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.archivos')),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.permisos')),
                ('id_usuario_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos_propietario', to='projects.usuarios')),
                ('id_usuario_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartidos_receptor', to='projects.usuarios')),
            ],
            options={
                'db_table': 'compartidos',
            },
        ),
        migrations.AddField(
            model_name='carpetas',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios'),
        ),
        migrations.AddField(
            model_name='archivos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.usuarios'),
        ),
    ]
